OrdersManager/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OrdersManager.Data.Enum;
using OrdersManager.Interfaces;
using OrdersManager.ViewModels;

namespace OrdersManager.Controllers;

public class DashboardController : Controller
{
    private readonly IDashboardRepository _dashboardRepository;
    private readonly IHttpContextAccessor _httpContextAccessor;

    public DashboardController(IDashboardRepository dashboardRepository, IHttpContextAccessor httpContextAccessor)
    {
        _dashboardRepository = dashboardRepository;
        _httpContextAccessor = httpContextAccessor;
    }

    [Authorize]
    public async Task<IActionResult> Index()
    {
        var userOrders = await _dashboardRepository.GetAllUserOrders();
        var curUser = _httpContextAccessor.HttpContext?.User.GetUserId();
        var user = await _dashboardRepository.GetUserById(curUser);
        var dashboardViewModel = new DashboardViewModel()
        {
            Orders = userOrders,
            User = user,
            Start = DateTime.Today,
            End = DateTime.Today
        };
        return View(dashboardViewModel);
    }

    [Authorize]
    public async Task<IActionResult> OrdersWithCurrentStatus(Status status)
    {
        var curUser = _httpContextAccessor.HttpContext?.User.GetUserId();
        var userOrders = await _dashboardRepository.GetAllUserOrdersWithStatus(status);
        var user = await _dashboardRepository.GetUserById(curUser);
        var ordersResult = new DashboardViewModel()
        {
            Orders = userOrders
        };

        return View(ordersResult);
    }
}

OrdersManager/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OrdersManager.Data;
using OrdersManager.Data.Enum;
using OrdersManager.Interfaces;
using OrdersManager.Models;
using OrdersManager.ViewModels;

namespace OrdersManager.Controllers;

public class OrderController : Controller
{
    private readonly IOrderRepository _orderRepository;
    private readonly ApplicationDbContext _context;
    private readonly IUserRepository _userRepository;
    private readonly IShopRepository _shopRepository;

    public OrderController(ApplicationDbContext context, IOrderRepository orderRepository, IUserRepository userRepository
    ,IShopRepository shopRepository)
    {
        _context = context;
        _orderRepository = orderRepository;
        _userRepository = userRepository;
        _shopRepository = shopRepository;
    }
    
    [Authorize(Roles="admin")]
    public async Task<IActionResult> Index(int page = 1)
    {
        int pageSize = 5;
        IQueryable<Order> source = _orderRepository.GetAllNew();
        var count = await source.CountAsync();
        var items = await source.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();
 
        PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
        IndexViewModel viewModel = new IndexViewModel
        {
            PageViewModel = pageViewModel,
            Orders = items
        };
        
        return View(viewModel);
    }

    [Authorize]
    public async Task<IActionResult> OrdersWithCurrentStatus(Status status, int page = 1)
    {
        int pageSize = 5;
        var source= _orderRepository.GetAllOrdersWithCurrentStatus(status);
        var count = await source.CountAsync();
        var items = await source.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();
        
        PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
        IndexViewModel viewModel = new IndexViewModel ()
        {
            PageViewModel = pageViewModel,
            Orders = items
        };

        return View(viewModel);
    }
    
    public async Task<IActionResult> Detail(int id)
    {
        Order order = await _orderRepository.GetByIdAsync(id);

        return View(order);
    }

    [Authorize(Roles="admin")]
    public async Task<IActionResult> Create()
    {
        var orderVM = new OrderProcessViewModel()
        {
            Boosters = await _userRepository.GetAllUsers(),
            Shops = await _shopRepository.GetAll()
        };
        return View(orderVM);
    }

    [Authorize(Roles="admin")]
    [HttpPost]
    public async Task<IActionResult> Create(OrderProcessViewModel orderVM)
    {
        
        if (!ModelState.IsValid)
        {
            orderVM.Boosters = await _userRepository.GetAllUsers();
            orderVM.Shops = await _shopRepository.GetAll();
            return View(orderVM);
        }
        
        AppUser appUser = _context.AppUsers.Where(c => c.Id == orderVM.BoosterId).FirstOrDefault();
        if (appUser == null)
        {
            return View(orderVM);
        }
        Shop shop = _context.Shops.Where(c => c.Id == orderVM.ShopId).FirstOrDefault();
        if (shop == null)
        {
            return View(orderVM);
        }
        
        orderVM.Booster = appUser;
        orderVM.Shop = shop;
        var order = new Order()
        {
            Booster = orderVM.Booster,
            Client = orderVM.Client,
            Shop = orderVM.Shop,
            StartDate = orderVM.StartDate,
            Payment = orderVM.Payment,
            status = orderVM.status,
            Description = orderVM.Description
        };
        
        _orderRepository.Add(order);
        _orderRepository.Save();
        return RedirectToAction("Index");

    }

    public async Task<IActionResult> Edit(int id)
    {

        var order = await _orderRepository.GetByIdAsyncNoTracking(id);

        var orderVM = new OrderProcessViewModel
        {
            Booster = order.Booster,
            Client = order.Client,
            Shop = order.Shop,
            StartDate = order.StartDate,
            Payment = order.Payment,
            status = order.status,
            Description = order.Description,
            Boosters = await _userRepository.GetAllUsers(),
            Shops = await _shopRepository.GetAll()
        };
        return View(orderVM);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(int id, OrderProcessViewModel orderVM)
    {
        if (User.IsInRole("user"))
        {
            var tempOrder = _orderRepository.GetByIdAsyncNoTracking(id).Result;
            var orderFromUser = new Order
            {
                Id = id,
                Booster = tempOrder.Booster,
                Client = tempOrder.Client,
                Shop = tempOrder.Shop,
                StartDate = tempOrder.StartDate,
                Payment = tempOrder.Payment,
                status = orderVM.status,
                Description = tempOrder.Description
            };
            if (orderFromUser.status == Status.Done)
            {
                orderFromUser.EndTime = DateTime.Now;
            }
            else
            {
                orderFromUser.EndTime = null;
            }
            _orderRepository.Update(orderFromUser);
        
            return RedirectToAction("Index", "Dashboard");
        }
        
        if (!ModelState.IsValid)
        {
            Shop shop = _context.Shops.Where(c => c.Id == orderVM.ShopId).FirstOrDefault();
            orderVM.Booster = await _userRepository.GetUserById(orderVM.BoosterId);
            orderVM.Shop = shop;
            orderVM.Boosters = await _userRepository.GetAllUsers();
            orderVM.Shops = await _shopRepository.GetAll();
            return View(orderVM);
        }
        AppUser appUser = _context.AppUsers.Where(c => c.Id == orderVM.BoosterId).FirstOrDefault();
        Shop editedShop = _context.Shops.Where(c => c.Id == orderVM.ShopId).FirstOrDefault();

        var order = new Order
        {
            Id = id,
            Booster = appUser,
            Client = orderVM.Client,
            Shop = editedShop,
            StartDate = orderVM.StartDate,
            Payment = orderVM.Payment,
            status = orderVM.status,
            Description = orderVM.Description
        };
        if (order.status == Status.Done)
        {
            order.EndTime = DateTime.Now;
        }
        else
        {
            order.EndTime = null;
        }
        _orderRepository.Update(order);
        
        return RedirectToAction("Index", "Dashboard");
    }
}

OrdersManager/Controllers/ReportsController.cs
using Microsoft.AspNetCore.Mvc;
using OrdersManager.Interfaces;
using OrdersManager.ViewModels;

namespace OrdersManager.Controllers;

public class ReportsController : Controller
{
    private readonly IReportsRepository _reportsRepository;
    private readonly IHttpContextAccessor _httpContextAccessor;

    public ReportsController(IReportsRepository reportsRepository, IHttpContextAccessor httpContextAccessor)
    {
        _reportsRepository = reportsRepository;
        _httpContextAccessor = httpContextAccessor;
    }
    
    public async Task<IActionResult> Index(DateTime start, DateTime end)
    {

        var userOrders = await _reportsRepository.GetAllCompletedUserOrders(start, end);
        //var curUser = _httpContextAccessor.HttpContext?.User.GetUserId();
        //var user = await _reportsRepository.GetUserById(curUser);

        Decimal totalPayment = 0;
        foreach (var item in userOrders)
        {
            totalPayment += item.Payment;
        }
        var reportsViewModel = new ReportsViewModel()
        {
            Orders = userOrders,
            TotalPayment = totalPayment
        };
        return View(reportsViewModel);
    }
    

}

OrdersManager/Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;
using OrdersManager.Data;
using OrdersManager.Interfaces;
using OrdersManager.Models;
using OrdersManager.ViewModels;

namespace OrdersManager.Controllers;

public class ShopController : Controller
{
    private readonly IShopRepository _shopRepository;
    private readonly IPhotoService _photoService;

    public ShopController(ApplicationDbContext context, IShopRepository shopRepository, IPhotoService photoService)
    {
        _shopRepository = shopRepository;
        _photoService = photoService;
    }
    
    public async Task<IActionResult> Index()
    {
        IEnumerable<Shop> shops = await _shopRepository.GetAll();

        return View(shops);
    }

    public async Task<IActionResult> Detail(int id)
    {
        Shop shop = await _shopRepository.GetByIdAsync(id);

        return View(shop);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(CreateShopViewModel shopVM)
    {
        if (ModelState.IsValid)
        {
            var result = await _photoService.AddPhotoAsync(shopVM.Image);

            var shop = new Shop
            {
                Name = shopVM.Name,
                Url = shopVM.Url,
                Image = result.Url.ToString()
            };
            _shopRepository.Add(shop);
            return RedirectToAction("Index");
        }
        else
        {
            ModelState.AddModelError("","Photo upload failed");
        }

        return View(shopVM);
    }
}

OrdersManager/Controllers/UserController.cs
using CloudinaryDotNet.Actions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OrdersManager.Data.Enum;
using OrdersManager.Interfaces;
using OrdersManager.Models;
using OrdersManager.ViewModels;

namespace OrdersManager.Controllers;

public class UserController : Controller
{
    private readonly IUserRepository _userRepository;
    private readonly IPhotoService _photoService;
    private readonly UserManager<AppUser> _userManager;

    public UserController(IUserRepository userRepository,  IPhotoService photoService, UserManager<AppUser> userManager)
    {
        _userRepository = userRepository;
        _photoService = photoService;
        _userManager = userManager;
    }
    
    private void MapUserEdit(AppUser user, EditUserViewModel editVM, ImageUploadResult photoResult)
    {
        user.Id = editVM.Id;
        if (photoResult != null)
        {
            user.ProfileImageUrl = photoResult.Url.ToString();
        }

        if (editVM.Password != null)
        {
            var passwordHasher = HttpContext.RequestServices.GetService(typeof(IPasswordHasher<AppUser>)) as IPasswordHasher<AppUser>;
            user.PasswordHash = passwordHasher.HashPassword(user, editVM.Password);
        }
        user.Email = editVM.Email;
        user.NormalizedEmail = editVM.Email.ToUpper();
    }
    
    [Authorize(Roles="admin")]
    [HttpGet("users")]
    public async Task<IActionResult> Index()
    {
        var users = await _userRepository.GetAllUsers();
        List<UserViewModel> result = new List<UserViewModel>();
        foreach (var user in users)
        {
            var userRoles = _userManager.GetRolesAsync(user).Result;
            var userViewModel = new UserViewModel()
            {
                Id = user.Id,
                UserName = user.UserName,
                Image = user.ProfileImageUrl,
                Role = userRoles.First()
            };
            result.Add(userViewModel);
        }
        return View(result);
    }

    public async Task<IActionResult> Detail(string id)
    {
        var user = await _userRepository.GetUserById(id);
        var userDetailViewModel = new UserDetailViewModel()
        {
            Id = user.Id,
            UserName = user.UserName,
            UserEmail = user.Email,
            Image = user.ProfileImageUrl
        };
        return View(userDetailViewModel);
    }
    
    public async Task<IActionResult> EditUserFromAdmin(string id)
    {
        var curUserId = id;
        var user = await _userRepository.GetUserById(curUserId);
        if (user == null)
        {
            return View("Error");
        }

        var editUserViewModel = new EditUserViewModel()
        {
            Id = curUserId,
            ProfileImageUrl = user.ProfileImageUrl,
            Email = user.Email,
            Password = user.PasswordHash
        };
        return View(editUserViewModel);
    }
    
    [HttpPost]
    public async Task<IActionResult> EditUserFromAdmin(EditUserViewModel editUserViewModel)
    {
        if (!ModelState.IsValid)
        {
            ModelState.AddModelError("", "Failed to edit profile");
            return View("EditUserFromAdmin", editUserViewModel);
        }

        var user = await _userRepository.GetByIdNoTracking(editUserViewModel.Id);
        if (user.ProfileImageUrl == "" || user.ProfileImageUrl == null)
        {
            var photoResult = await _photoService.AddPhotoAsync(editUserViewModel.Image);
            MapUserEdit(user, editUserViewModel, photoResult);

            _userRepository.Update(user);
            return RedirectToAction("EditUserFromAdmin");
        }
        else
        {
            try
            {
                if (editUserViewModel.Image != null)
                {
                    await _photoService.DeletePhotoAsync(user.ProfileImageUrl);
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", "Could not delete photo");
                return View(editUserViewModel);
            }
            if (editUserViewModel.Image != null)
            {
                var photoResult = await _photoService.AddPhotoAsync(editUserViewModel.Image);
                MapUserEdit(user, editUserViewModel, photoResult);
            }
            else
            {
                ImageUploadResult photoResult = null;
                MapUserEdit(user, editUserViewModel, photoResult);
            }

            _userRepository.Update(user);
            return RedirectToAction("EditUserFromAdmin");
        }
    }

    [Authorize(Roles="admin")]
    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }
    
    [Authorize(Roles="admin")]
    [HttpPost]
    public async Task<IActionResult> Create(CreateUserViewModel userVM)
    {
        if (!ModelState.IsValid)
        {
            return View(userVM);
        }
        AppUser user = new AppUser()
        {
            Email = userVM.Email,
            UserName = userVM.UserName
        };

        var result = await _userManager.CreateAsync(user, userVM.Password);
        if (result.Succeeded)
        {
            await _userManager.AddToRoleAsync(user, UserRoles.User);
            return RedirectToAction("Index", "Home");
        }
        else
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
        }
        return View(userVM);
    }
    public async Task<ActionResult> LockOut(string id)
    {
        AppUser user = await _userManager.FindByIdAsync(id);

        if (user != null)
        { 
           await _userManager.RemoveFromRoleAsync(user, UserRoles.User);
           await _userManager.AddToRoleAsync(user, UserRoles.Block);
        }

        return RedirectToAction("Index");
    }
    public async Task<ActionResult> UnLockOut(string id)
    {
        AppUser user = await _userManager.FindByIdAsync(id);

        if (user != null)
        {
            await _userManager.RemoveFromRoleAsync(user, UserRoles.Block);
            await _userManager.AddToRoleAsync(user, UserRoles.User);
        }

        return RedirectToAction("Index");
    }
}

OrdersManager/Views/Dashboard/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using System.Security.Claims
@using OrdersManager.Data.Enum
@inject SignInManager<AppUser> SignInManager

@model OrdersManager.ViewModels.DashboardViewModel

<div class="row">
  <div class="col-md-2">
    <h3>Hello, @Model.User.UserName</h3>
  </div>
  <div class="col-md-4">
    <img src="@Model.User.ProfileImageUrl" alt="Card image cap" width="50" height="50">    
  </div>
</div>
<div class="row">
  <div class="col-md-4">
    <div class="overlay"></div>
    <h4>Select dates for report</h4>
    <form method="get" asp-action="Index" enctype="multipart/form-data">
      <div class="mb-3">
        <label asp-for="Start" class="form-label">From</label>
        <input asp-for="Start" class="form-control" aria-describedby="emailHelp">
        <span asp-validation-for="Start" class="text-danger"></span>
      </div>
      <div class="mb-3">
        <label asp-for="End" class="form-label">To</label>
        <input asp-for="End" class="form-control" aria-describedby="emailHelp">
        <span asp-validation-for="End" class="text-danger"></span>
      </div>
      <button type="submit" class="btn btn-primary" asp-controller="Reports" asp-action="Index">Generate</button>
    </form>
  </div>
  <div class="col-md-8">
    <h4>Your orders</h4>
    <form method="get" asp-action="Index" enctype="multipart/form-data">
      <div class="mb-3">
        <input type="hidden" asp-for="Status" class="form-control" aria-describedby="emailHelp" value="@Status.Done">
      </div>
      <button type="submit" class="btn btn-primary" asp-controller="Dashboard" asp-action="OrdersWithCurrentStatus">Done orders</button>
    </form>
    <form method="get" asp-action="Index" enctype="multipart/form-data">
      <div class="mb-3">
        <input type="hidden" asp-for="Status" class="form-control" aria-describedby="emailHelp" value="@Status.InProgress">
      </div>
      <button type="submit" class="btn btn-primary" asp-controller="Dashboard" asp-action="OrdersWithCurrentStatus">InProgress orders</button>
    </form>
    <form method="get" asp-action="Index" enctype="multipart/form-data">
      <div class="mb-3">
        <input type="hidden" asp-for="Status" class="form-control" aria-describedby="emailHelp" value="@Status.NotStarted">
      </div>
      <button type="submit" class="btn btn-primary" asp-controller="Dashboard" asp-action="OrdersWithCurrentStatus">NotStarted orders</button>
    </form>
    <div class="mt-3">
      <h4>Edite your profile</h4>
      <a asp-controller="User" asp-action="EditUserFromAdmin" asp-route-id="@Model.User.Id" class="btn btn-sm btn-outline-secondary">Edit</a>
    </div>
  </div>
</div>

@if (User.IsInRole("admin"))
{
  <div class="mt-2 row btn-group col-md-2">
    <a asp-controller="Order" asp-action="Create" class="btn btn-sm btn-outline-primary mt-2">Add new order</a>
    <a asp-controller="Shop" asp-action="Create" class="btn btn-sm btn-outline-primary mt-2">Add new shop</a>
    <a asp-controller="User" asp-action="Create" class="btn btn-sm btn-outline-primary mt-2">Add new user</a>
  </div>  
}

OrdersManager/Views/Dashboard/OrdersWithCurrentStatus.cshtml
@using OrdersManager.Data.Enum
@model OrdersManager.ViewModels.DashboardViewModel

<table class="table">
    <tbody>
    @foreach (var item in Model.Orders)
    {
        <tr>
    <div class="row mt-3">
        <div class="col-md-2">
            <p class="card-text m-0"><strong>Start:</strong> @item.StartDate</p>
            <p class="card-text m-0"><strong>Price:</strong> @item.Payment</p>
            <p class="card-text m-0"><strong>Booster:</strong> @item.Booster.UserName</p>
            <p class="card-text m-0">
                <a asp-controller="Order" asp-action="Detail" asp-route-id="@item.Id" type="button" class="btn btn-sm btn-outline-secondary">View</a>
                @if (User.Identity.IsAuthenticated && @item.status != Status.Done)
                {   
                    <a asp-controller="Order" asp-action="Edit" asp-route-id="@item.Id" type="button" class="btn btn-sm btn-outline-secondary">Edit</a>
                }
                @if (User.Identity.IsAuthenticated && User.IsInRole("admin") && item.status == Status.Done)
                {   
                    <a asp-controller="Order" asp-action="Edit" asp-route-id="@item.Id" type="button" class="btn btn-sm btn-outline-secondary">Edit</a>
                }
            </p>
        </div>
        <div class="col-md-2">
            <img src="@item.Shop.Image" alt="Card image cap" class="card-img-top" width="70%" height="70%">
        </div>
    </div>
    </tr>
    }
    </tbody>
</table>